name: Release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
          
      - name: Install dependencies
        run: bun install
        
      - name: Run tests
        run: bun run test:run
        
      - name: Type check
        run: bun run compile
        
      - name: Build extension
        run: bun run build
        
      - name: Package Chrome extension
        run: bun run zip
        
      - name: Get version without v prefix
        id: get_version
        run: |
          VERSION="${{ github.event.release.tag_name }}"
          echo "version=${VERSION#v}" >> $GITHUB_OUTPUT
      
      - name: Upload Chrome extension
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_GH_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./.output/webpage-table-exporter-${{ steps.get_version.outputs.version }}-chrome.zip
          asset_name: webpage-table-exporter-${{ steps.get_version.outputs.version }}-chrome.zip
          asset_content_type: application/zip
